name: Simple Workflow

on:
  workflow_dispatch:  # This event triggers the workflow manually

jobs:
  deploy:
    runs-on: self-hosted

    steps:

      - name: Deploy to Server
        run: |
          touch a.txt